setwd('/home/tjsipin/will_tj')
source('src_lowFilter_v5_50km/temp/02_wy_bg.R')
source('src_lowFilter_v5_50km/R_WY/03_buildModels.R')
source('src_lowFilter_v5_50km/R_WY/04_predictions.R')
source('src_lowFilter_v5_50km/R_WY/05_plotting.R')